import json

import real2sim_scene_foundry.gaussian_splat_assets as gaussian_splat_assets
from real2sim_scene_foundry.gaussian_splat_assets import (
    build_gaussian_splat_asset_report,
    parse_gaussian_splat_ply_header,
    write_gaussian_splat_asset_report,
)


def test_parse_gaussian_splat_ply_header_reads_count_format_and_required_fields(tmp_path):
    asset = tmp_path / "background" / "3dgs_native" / "splat_rgb.ply"
    asset.parent.mkdir(parents=True)
    asset.write_bytes(
        b"\n".join(
            [
                b"ply",
                b"format binary_little_endian 1.0",
                b"comment Generated by Nerfstudio",
                b"element vertex 12",
                b"property float x",
                b"property float y",
                b"property float z",
                b"property uchar red",
                b"property uchar green",
                b"property uchar blue",
                b"property float opacity",
                b"property float scale_0",
                b"property float scale_1",
                b"property float scale_2",
                b"property float rot_0",
                b"property float rot_1",
                b"property float rot_2",
                b"property float rot_3",
                b"end_header",
                b"",
            ]
        )
    )

    header = parse_gaussian_splat_ply_header(asset)

    assert header.gaussian_count == 12
    assert header.format == "binary_little_endian 1.0"
    assert header.required_fields_present["x"] is True
    assert header.required_fields_present["rgb"] is True
    assert header.missing_required_fields == []


def test_write_gaussian_splat_asset_report_is_asset_only_not_runtime_proof(tmp_path):
    asset = tmp_path / "background" / "3dgs_native" / "splat_rgb.ply"
    asset.parent.mkdir(parents=True)
    asset.write_text(
        "\n".join(
            [
                "ply",
                "format ascii 1.0",
                "element vertex 2",
                "property float x",
                "property float y",
                "property float z",
                "property uchar red",
                "property uchar green",
                "property uchar blue",
                "property float opacity",
                "property float scale_0",
                "property float scale_1",
                "property float scale_2",
                "property float rot_0",
                "property float rot_1",
                "property float rot_2",
                "property float rot_3",
                "end_header",
                "0 0 0 255 0 0 1 0 0 0 1 0 0 0",
                "1 0 0 0 255 0 1 0 0 0 1 0 0 0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    report_path = write_gaussian_splat_asset_report(asset)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert report_path == asset.parent / "asset_report.json"
    assert report["status"] == "asset_format_complete"
    assert report["asset_path"] == str(asset)
    assert report["gaussian_count"] == 2
    assert report["format"] == "ascii 1.0"
    assert report["required_fields_present"]["rgb"] is True
    assert report["blocked_reason"] is None
    assert report["simulator_native_rendering"]["status"] == "not_verified"
    assert report["simulator_native_rendering"]["native_rendering_proven"] is False
    assert "asset exists" in report["scope_note"]


def test_build_gaussian_splat_asset_report_blocks_missing_required_fields(tmp_path):
    asset = tmp_path / "background" / "3dgs_native" / "splat_rgb.ply"
    asset.parent.mkdir(parents=True)
    asset.write_text(
        "\n".join(
            [
                "ply",
                "format ascii 1.0",
                "element vertex 3",
                "property float x",
                "property float y",
                "property float z",
                "property uchar red",
                "property uchar green",
                "property uchar blue",
                "property float opacity",
                "property float scale_0",
                "property float scale_1",
                "end_header",
                "0 0 0 255 255 255 1 0 0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    report = build_gaussian_splat_asset_report(asset)

    assert report["status"] == "blocked_missing_required_fields"
    assert report["gaussian_count"] == 3
    assert report["required_fields_present"]["scale_2"] is False
    assert report["required_fields_present"]["rot_0"] is False
    assert "scale_2" in report["blocked_reason"]
    assert report["proxy_conversion"]["generated"] is False
    assert "Do not promote" in report["proxy_conversion"]["caveat"]


def test_write_background_3dgs_runtime_report_marks_external_render_as_partial(tmp_path):
    run = tmp_path / "run"
    asset = run / "background" / "3dgs_native" / "splat_rgb.ply"
    _write_valid_splat(asset)
    render = run / "qa" / "background_3dgs_render.png"
    render.parent.mkdir(parents=True)
    render.write_bytes(b"png")
    (run / "qa" / "background_3dgs_render_report.json").write_text(
        json.dumps(
            {
                "status": "rendered",
                "backend": "external_3dgs_renderer",
                "registered_3dgs_rendered": True,
                "simulator_native": False,
                "render_path": "qa/background_3dgs_render.png",
            }
        ),
        encoding="utf-8",
    )

    assert hasattr(gaussian_splat_assets, "write_background_3dgs_runtime_report")
    report_path = gaussian_splat_assets.write_background_3dgs_runtime_report(run)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert report_path == run / "qa" / "background_3dgs_runtime_report.json"
    assert report["status"] == "partial_external_render_only"
    assert report["status"] != "passed"
    assert report["asset_schema"]["status"] == "asset_format_complete"
    assert report["external_render"]["status"] == "rendered"
    assert report["external_render"]["reference_view_only"] is True
    assert report["native_runtime_supported"] is False
    assert report["native_viewer_runtime"]["status"] == "unsupported"
    assert report["native_simulator_runtime"]["status"] == "unsupported"


def test_write_background_3dgs_runtime_report_blocks_schema_only_asset(tmp_path):
    run = tmp_path / "run"
    _write_valid_splat(run / "background" / "3dgs_native" / "splat_rgb.ply")

    assert hasattr(gaussian_splat_assets, "write_background_3dgs_runtime_report")
    report_path = gaussian_splat_assets.write_background_3dgs_runtime_report(run)
    report = json.loads(report_path.read_text(encoding="utf-8"))

    assert report["status"] == "blocked_native_3dgs_runtime"
    assert report["status"] != "passed"
    assert report["asset_schema"]["status"] == "asset_format_complete"
    assert report["external_render"]["status"] == "missing"
    assert "native viewer/simulator runtime loading is not verified" in report["blocked_reason"]


def _write_valid_splat(asset):
    asset.parent.mkdir(parents=True)
    asset.write_text(
        "\n".join(
            [
                "ply",
                "format ascii 1.0",
                "element vertex 1",
                "property float x",
                "property float y",
                "property float z",
                "property uchar red",
                "property uchar green",
                "property uchar blue",
                "property float opacity",
                "property float scale_0",
                "property float scale_1",
                "property float scale_2",
                "property float rot_0",
                "property float rot_1",
                "property float rot_2",
                "property float rot_3",
                "end_header",
                "0 0 0 255 255 255 1 0 0 0 1 0 0 0",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
